jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Install Apache Ant 1.9.9
        run: |
          wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.9.9-bin.zip
          unzip apache-ant-1.9.9-bin.zip
          sudo mv apache-ant-1.9.9 /usr/local/ant
          export PATH=$PATH:/usr/local/ant/bin
      
      - name: Build the project
        env:
          VERSION: ${{ github.ref }}.${{ github.sha }}
        run: ant -Dplugin.version=${VERSION}

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            dist/datapower-v*.zip
            dist/dcm.jar
